# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x10hyperagent.agent\x1a\x0c\x63ommon.proto\";\n\x0fRegisterRequest\x12\x12\n\nagent_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\"6\n\x10RegisterResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\"$\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"\x1f\n\x11HeartbeatResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"H\n\x10StartTaskRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"6\n\x11StartTaskResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07task_id\x18\x02 \x01(\t\"\"\n\x0fStopTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x1e\n\x10StopTaskResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xa9\x03\n\x05\x41gent\x12Q\n\x08Register\x12!.hyperagent.agent.RegisterRequest\x1a\".hyperagent.agent.RegisterResponse\x12T\n\tHeartbeat\x12\".hyperagent.agent.HeartbeatRequest\x1a#.hyperagent.agent.HeartbeatResponse\x12T\n\tStartTask\x12\".hyperagent.agent.StartTaskRequest\x1a#.hyperagent.agent.StartTaskResponse\x12N\n\nStreamLogs\x12\".hyperagent.agent.StartTaskRequest\x1a\x1a.hyperagent.common.LogLine0\x01\x12Q\n\x08StopTask\x12!.hyperagent.agent.StopTaskRequest\x1a\".hyperagent.agent.StopTaskResponseB&Z$hyperagent/manager/proto/agent;agentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$hyperagent/manager/proto/agent;agent'
  _globals['_REGISTERREQUEST']._serialized_start=47
  _globals['_REGISTERREQUEST']._serialized_end=106
  _globals['_REGISTERRESPONSE']._serialized_start=108
  _globals['_REGISTERRESPONSE']._serialized_end=162
  _globals['_HEARTBEATREQUEST']._serialized_start=164
  _globals['_HEARTBEATREQUEST']._serialized_end=200
  _globals['_HEARTBEATRESPONSE']._serialized_start=202
  _globals['_HEARTBEATRESPONSE']._serialized_end=233
  _globals['_STARTTASKREQUEST']._serialized_start=235
  _globals['_STARTTASKREQUEST']._serialized_end=307
  _globals['_STARTTASKRESPONSE']._serialized_start=309
  _globals['_STARTTASKRESPONSE']._serialized_end=363
  _globals['_STOPTASKREQUEST']._serialized_start=365
  _globals['_STOPTASKREQUEST']._serialized_end=399
  _globals['_STOPTASKRESPONSE']._serialized_start=401
  _globals['_STOPTASKRESPONSE']._serialized_end=431
  _globals['_AGENT']._serialized_start=434
  _globals['_AGENT']._serialized_end=859
# @@protoc_insertion_point(module_scope)
